Repository buildo/toctoc, pull requests merged in 2018-02, with the labels that each got.

#28 Adding ts declarations to release (closes #29)
  web/.babelrc
  web/metarpheus-config.js
  web/metarpheus-ts-config.js
  web/package.json
  web/src/SessionSerializer/SessionSerializer.ts
  web/src/api.js
  web/src/api.ts
  web/src/index.ts
  web/src/metarpheus/api-ts.ts
  web/src/metarpheus/api.js
  web/src/metarpheus/model-ts.ts
  web/src/metarpheus/model.js
  web/src/model.js
  web/src/model.ts
  web/tsconfig.json
  web/yarn.lock
Labels: bug, in review

#31 #30: Update READMEs with release notes and remove smooth-release (closes #30)
  README.md
  web/README.md
  web/package.json
  web/yarn.lock
Labels: waiting for merge

#26 Quill tests
  backend/project/Dependencies.scala
  backend/quill/src/main/scala/io.buildo.toctoc/quill/authentication/token/QuillAccessTokenAuthenticationDomain.scala
  backend/quill/src/test/resources/db/migration/V0__schema.sql
  backend/quill/src/test/resources/reference.conf
  backend/quill/src/test/scala/io.buildo.toctoc/quill/authentication/test/QuillLoginAuthenticationDomainFlowSpec.scala
  backend/slick/src/main/scala/io.buildo.toctoc/slick/authentication/login/SlickLoginAuthenticationDomain.scala
Labels: in review

#33 #5: make tests independent (closes #5)
  .drone.yml
  backend/quill/src/test/scala/io.buildo.toctoc/quill/authentication/test/QuillLoginAuthenticationDomainFlowSpec.scala
  backend/slick/src/test/scala/io.buildo.toctoc/slick/authentication/test/SlickLoginAuthenticationDomainFlowSpec.scala
Labels: tech debt, waiting for merge
